### ISSUE TITLE
Feedback if no query passed

### ISSUE THREAD

**Issue by Philmod** [auth0-community/socketio-jwt#24]
Hi,

I'm using the one roundtrip technique with socket.io<1

``` js
io.set('authorization', socketioJwt.authorize({
  secret: 'your secret or public key',
  handshake: true
}));
```

But if the client doesn't pass the token, he doesn't receive any feedback. Is there a `timeout` so set? Or a event to listen to?

Thanks,
Philmod

**Comment by zooteradmin** [comment]
Any update on this ??

**Comment by beardaway** [comment]
Hey there everyone!

Terribly sorry for such delay in response! At the time the tool hosted in the repo was developed we didn't have enough bandwidth to implement it further that's why we kinda decided to "outsource" it to our community developers.

For now we are gradually expanding the team and we're aiming that at some point in the future we'll be able to maintain and develop this repo more effectively. Sorry for any inconvenience!
