### ISSUE TITLE
Blacklisting tokens

### ISSUE THREAD

**Issue by CraigChilds94** [auth0-community/socketio-jwt#87]
It appears as though there's no built in mechanism to ensure that tokens being passed to the socket are not blacklisted, I wondered if you had any plans to add this?

**Comment by beardaway** [comment]
Hey there @CraigChilds94 !

Terribly sorry for such delay in response! At the time the tool hosted in the repo was developed we didn't have enough bandwidth to implement it further that's why we kinda decided to "outsorce" it to our community developers.

For now we are gradually expanding the team and we're aiming that at some point in the future we'll be able to maintain and develop this repo more effectively. Sorry for any inconvenience!
